policies:
  - type: commit
    spec:
      header:
        length: 89
        invalidLastCharacters: .
      body:
        required: false
      dco: false
      gpg:
        required: false
      spellcheck:
        locale: US
      conventional:
        types:
          - "feat"
          - "fix"
          - "docs"
        scopes:
          - "scope"
        descriptionLength: 72
  - type: license
    spec:
      skipPaths:
        - .git/
        - .build*/
      includeSuffixes:
        - .ext
      excludeSuffixes:
        - .exclude-ext-prefix.ext
      allowPrecedingComments: false
      header: |
        This is the contents of a license header.